language: scala
scala:
  - 2.10.4
  - 2.11.5
jdk:
  - oraclejdk7
  - openjdk7
script:
  - travis_retry sbt clean coverage test &&
    sbt coverageAggregate
after_success:
  - bash <(curl -s https://codecov.io/bash)
